<?php

namespace AppBundle\Repository;

/**
 * CodeQrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeQrRepository extends \Doctrine\ORM\EntityRepository
{
}
