<?php

namespace AppBundle\Repository;

/**
 * FluxSortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FluxSortieRepository extends \Doctrine\ORM\EntityRepository
{
}
