<?php

namespace AppBundle\Repository;

/**
 * FluxEntreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FluxEntreeRepository extends \Doctrine\ORM\EntityRepository
{
}
