<?php

namespace AppBundle\Repository;

/**
 * ModaliteAccesEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModaliteAccesEvenementRepository extends \Doctrine\ORM\EntityRepository
{
}
