<?php

namespace AppBundle\Repository;

/**
 * OeuvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OeuvreRepository extends \Doctrine\ORM\EntityRepository
{
}
