<?php

namespace AppBundle\Repository;

/**
 * TypeEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEvenementRepository extends \Doctrine\ORM\EntityRepository
{
}
